#Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: Lauren Kelly
url: 'https://unreality.me'
baseurl: '' #change it according to your repository name
description: Senior Technical Program Manager with a record of architecting and scaling enterprise programs that align cross-functional teams, optimize technical execution, and drive measurable business outcomes in AI/ML, data infrastructure, and platform transformation.
# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: blue # blue turquoise green berry orange ceramic
chrome_mobile_color: #use hex colors (ex:#1976d2) or leave empty if you don't want a color for chrome mobile searchbar

# Tracker
analytics: G-QE81JK440N

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 0.0.0.0
safe: false
